targets:
  - word: bank
    senses:
      finance: ["financ", "bank", "money"]
      river: ["river", "water"]
  - word: run
    senses:
      election: ["office"]
      management: ["project"]
  - word: bat
    senses:
      animal: ["animal", "mammal"]
      sports: ["stick", "baseball", "ball"]
  - word: pitch
    senses:
      music: ["sound"]
      sports: ["throw", "baseball", "ball"]
